kind: ImageStream
apiVersion: v1
metadata:
  name: memcached
  creationTimestamp: null
spec:
  tags:
    - name: latest
      from:
        Kind: ImageStreamTag
        Name: "1.4"
    - name: "1.4"
      from:
        Kind: DockerImage
        Name: getupcloud/memcached:latest
