apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  name: php-extra
spec:
  tags:
  - annotations:
      description: Build and run PHP 5.5 applications, with extra packages
      iconClass: icon-php
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:5.5,php
      tags: builder,php
      version: "5.5"
    from:
      kind: DockerImage
      name: getupcloud/sti-php-extra:5.5
    name: "5.5"
  - annotations:
      description: Build and run PHP 5.6 applications, with extra packages
      iconClass: icon-php
      sampleRepo: https://github.com/openshift/cakephp-ex.git
      supports: php:5.6,php
      tags: builder,php
      version: "5.6"
    from:
      kind: DockerImage
      name: getupcloud/sti-php-extra:5.6
    name: "5.6"
  - from:
      kind: DockerImage
      name: getupcloud/sti-php-extra:latest
    name: latest
