apiVersion: v1
kind: ImageStream
metadata:
  annotations: null
  creationTimestamp: null
  name: cron
spec:
  tags:
  - name: latest
    from:
      kind: ImageStreamTag
      name: base
  - name: base
    annotations:
      description: Cron for docker - base image
      iconClass: icon-mascot
      sampleRepo: https://github.com/getupcloud/sti-cron.git
      supports: cron:1.0,cron
      tags: builder,cron,jobs
      version: "1.0"
    from:
      kind: DockerImage
      name: getupcloud/cron-base-centos7
  - name: ruby19
    annotations:
      description: Cron for docker - ruby-1.9 image
      iconClass: icon-ruby
      sampleRepo: https://github.com/getupcloud/sti-cron.git
      supports: cron:1.0,cron,ruby:1.9,ruby
      tags: builder,cron,jobs,ruby
      version: "1.0"
    from:
      kind: DockerImage
      name: getupcloud/cron-ruby-19-centos7
  - name: ruby20
    annotations:
      description: Cron for docker - ruby-2.0 image
      iconClass: icon-ruby
      sampleRepo: https://github.com/getupcloud/sti-cron.git
      supports: cron:1.0,cron,ruby:2.0,ruby
      tags: builder,cron,jobs,ruby
      version: "1.0"
    from:
      kind: DockerImage
      name: getupcloud/cron-ruby-20-centos7
  - name: php56
    annotations:
      description: Cron for docker - php-5.6 image
      iconClass: icon-php
      sampleRepo: https://github.com/getupcloud/sti-cron.git
      supports: cron:1.0,cron,php:5.6,php
      tags: builder,cron,jobs,php
      version: "1.0"
    from:
      kind: DockerImage
      name: getupcloud/cron-php-56-centos7
