apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  name: jruby
spec:
  tags:
  - name: "1.7"
    annotations:
      description: Build and run JRuby 1.7 applications
      iconClass: icon-jruby
      sampleRepo: https://github.com/getupcloud/rails3-ex.git
      supports: jruby:1.7,jruby
      tags: builder,jruby
      version: "1.7"
    from:
      kind: DockerImage
      name: getupcloud/jruby-17-centos7:latest
  - name: latest
    from:
      kind: ImageStreamTag
      name: jruby:1.7
